### ISSUE TITLE
Part 1.1: Explore New Feeds

### ISSUE THREAD

**Issue by ykomal** [Egnite-git/ds-python-du-Ananth-R#1]

**Comment by Ananth-R** [comment]
@ykomal , @Monish-k 
I would like to use the RSS feed from 
www.towardsdatascience.com
http://www.analyticsvidhya.com/blog/
https://github.com/rushter/
https://blog.datasciencedojo.com/
http://fivethirtyeight.com/
http://blogs.forrester.com/category/big_data
http://www.ibmbigdatahub.com/blog
https://www.kdnuggets.com/
https://www.oreilly.com/topics/data-science
https://www.oreilly.com/ideas
http://blogs.oracle.com/datamining/
http://planetbigdata.com/
http://www.r-bloggers.com/
http://blogs.sas.com/content/
http://blogs.sas.com/content/sascom/
http://smartdatacollective.com/
http://www.statsblogs.com/
https://blogs.oracle.com/datawarehousing/
https://ai4.io/blog/
https://analyticstrategy.com/news/
http://www.thejuliagroup.com/blog/
https://annalyzin.wordpress.com/
http://www.arilamstein.com/blog
http://www.beyondtheboxscore.com/
http://bigdatatobigprofits.com/
http://www.zdnet.com/blog/big-data/
https://blogstats.wordpress.com/
http://practicalanalytics.wordpress.com/
http://www.bzst.com/
http://www.calculatedriskblog.com/
http://blog.cluster-text.com/
http://cooldata.wordpress.com/
https://www.scnsoft.com/blog/category/data-analytics
http://www.datagenetics.com/blog
http://www.dataminingblog.com/
http://datamining.typepad.com/data_mining/
http://data-mining.philippe-fournier-viger.com/
http://101.datascience.community/
http://www.becomingadatascientist.com/
http://www.datatau.com/
http://data36.com/
http://www.dataquest.io/blog/
http://www.decisionstats.com/
http://www.deep-data-mining.com/
http://blog.dominodatalab.com/
http://bigdatablog.emc.com/
https://www.eminenture.com/blog/
http://errorstatistics.com/
https://www.facebook.com/data?_rdr=p
http://fastml.com/
http://fbhalper.wordpress.com/
http://flowingdata.com/
http://freakonometrics.hypotheses.org/
http://www.freakonomics.com/blog/
http://glinden.blogspot.com/
http://goranxview.blogspot.com/
http://harvarddatascience.com/
https://community.havenondemand.com/t5/Blog/bg-p/blog_iod#
http://hunch.net/
http://robjhyndman.com/hyndsight/
http://www.ibmbigdatahub.com/blog
http://www.informationisbeautiful.net/blog/
https://www.innoarchitech.com/
http://www.insightdatascience.com/blog/
https://jmanton.wordpress.com/
http://jtonedm.com/
http://www.juiceanalytics.com/writing/
https://justindomke.wordpress.com/
http://blog.kaggle.com/
http://bickson.blogspot.com/
http://learninglover.com/blog/
http://lingpipe-blog.com/
https://lovestats.wordpress.com/
http://machinelearningmastery.com/blog/
http://www.machinedlearnings.com/
http://magnus-notitia.blogspot.com.tr/
http://www.mdmgeek.com/
http://blog.minethatdata.com/
http://net-savvy.com/executive/
http://nuit-blanche.blogspot.in/
http://junkcharts.typepad.com/numbersruleyourworld/
http://observationalepidemiology.blogspot.com/
http://www.opengardensblog.futuretext.com/
http://www.overcomingbias.com/
http://prateekvjoshi.com/author/prateekvjoshi/
http://www.predictiveanalyticsworld.com/blog/
http://www.statisticsblog.com/
http://www.r-chart.com/
http://www.r-statistics.com/
http://yyue.blogspot.in/
http://blog.revolutionanalytics.com/
http://athena-solutions.com/datadoghouse/
http://rgrossman.com/
http://blog.philbirnbaum.com/
http://info.salford-systems.com/
http://www.sasanalysis.com/
http://www.sas-programming.com/
http://shapeofdata.wordpress.com/
http://www.svds.com/
http://simplystatistics.org/
https://www.smarten.com/blog/
https://statisfaction.wordpress.com/
http://andrewgelman.com/
http://statistically-funny.blogspot.co.uk/
https://blog.statsbot.co/
http://statswithcats.wordpress.com/
http://www.information-management.com/blog/steve_miller.html
http://www.tatvic.com/blog/
http://www.theanalysisfactor.com/
http://www.badscience.net/
http://geomblog.blogspot.in/
http://www.theguardian.com/data
http://www.johndcook.com/blog/
http://themainstreamseer.blogspot.com/
http://practicalquant.blogspot.com/
http://bactra.org/weblog/
http://www.tomhcanderson.com/
http://www.analyticbridge.com/profile/VincentGranville
http://www.walkingrandomly.com/
http://whatsthebigdata.com/
https://xianblog.wordpress.com/
